name: Build
on:
  pull_request:
  push:
    branches:
      - configure-ci
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Set up Java 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Set up Java 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Set Permisions to Gradlew file
        run: 'chmod +x ./gradlew'
      - name: Build with Gradle
        run: './gradlew assembleDebug --info'
        env:
          MANGO_DOMAIN: ${{ secrets.MANGO_DOMAIN }}
          TESTS_MANGO_EMAIL: ${{ secrets.TESTS_MANGO_EMAIL }}
          TESTS_MANGO_PASSWORD: ${{ secrets.TESTS_MANGO_PASSWORD }}
          TEST_MANGO_NEW_PASSWORD: ${{ secrets.TEST_MANGO_NEW_PASSWORD }}
          TESTS_MANGO_IMAGE: ${{ secrets.TESTS_MANGO_IMAGE }}
      
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
