name: Build
on:
  pull_request:
  push:
    branches:
      - configure-ci
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Set up Java 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Set up Java 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Set Permisions to Gradlew file
        run: 'chmod +x ./gradlew'
      - name: Build with Gradle
        run: './gradlew build --info --debug'
      
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
